config/routes.rb
Books::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'admin', }
  as :user do
    get "/admin" => "devise/sessions#new"
  end

  root 'books#index'

  resources :books do
    collection do
      get 'page/:page', :action => :index
    end

    resources :reviews
    resources :assets, :only => [:index, :create, :destroy, :show] do
      get 'convert'
    end
  end

  get ':genre' => 'books#index', :as => 'genre'

end

app/models/book.rb
class Book < ActiveRecord::Base

  GENRES = %w(Sci-Fi Fiction Non-Fiction Tragedy Mystery Fantasy Mythology)

  validates :title, :author, :genre, :published_on, presence: true

  validates :image_file_name, allow_blank: true, format: {
    with: /\w+.(gif|jpg|png)\z/i,
    message: 'must reference a GIF, JPG, or PNG image'
  }

  validates :genre, inclusion: { in: GENRES }, unless: 'genre.blank?'

  scope :by, ->(author) { where('author = ?', author) }
  default_scope { order('created_at') }

  has_many :reviews, dependent: :destroy
  has_many :assets, dependent: :destroy

  def average_stars
    if reviews.loaded?
      reviews.map(&:stars).average
    else
      reviews.average(:stars)
    end
  end

  def recent_reviews(recent_count = 2)
    reviews.order('created_at desc').limit(recent_count)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  respond_to :html, :xml, :json

  before_action :set_book,
                only: [:show, :edit, :update, :destroy]

  before_action :set_genre

  before_action :signed_in,
                only: [:new]

  def index
    @books = list_books
    respond_with @books
  end

  def signed_in
    unless signed_in?
      redirect_to "/users/admin"
    end
  end

  def bargains
    @books = list_books.bargains
    respond_with @books
  end

  def show
    respond_with @book
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    flash[:notice] = "#{@book.title} was created!" if @book.save
    respond_with @book
  end

  def edit
  end

  def update
    flash[:notice] = "#{@book.title} was updated!" if @book.update(book_params)
    respond_with @book
  end

  def destroy
    @book.destroy
    redirect_to books_url, alert: "#{@book.title} was deleted!"
  end

  private
  def set_genre
    @genres = Book::GENRES
  end

  private

  def set_specials_flash
    flash[:notice] = "Today's special is 30% off all Sci-Fi books!"
  end

  def list_books
    unless params[:genre]
      Book.includes(:reviews).order(:title).page params[:page]
    else
      Book.includes(:reviews).where(:genre => params[:genre]).order(:title).page params[:page]
    end
  end

  def book_params
    params.require(:book).permit(:title, :abstract, :author, :pages, :image_file_name, :genre, :published_on)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def formatted_time(time)
    time.strftime('%B %d, %Y at %l:%M %p')
  end

  def image_for(book)
    file_name = book.image_file_name.blank? ? 'placeholder.png' : book.image_file_name
    image_tag(file_name, class: 'img-rounded', size: '90x120')
  end

  def format_average_stars(book)
    average = number_with_precision(book.average_stars, precision: 1)
    if average
      pluralize(average, 'star')
    else
      content_tag(:span, 'No reviews', { class: 'text-muted' })
    end
  end
end

app/views/books/_average_stars.html.erb
<%= format_average_stars(book) %>
<% if book.reviews.any? %>
  <span class="text-muted">(out of <%= pluralize(book.reviews.size, 'review') %>)</span>
<% end %>

app/views/books/_form.html.erb
<%= form_for(@book, html:{class: 'form-horizontal'}) do |f| %>
  <%= render 'shared/errors', object: @book %>

  <%= bootstrap_form_field(f, :title) do %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, :author) do %>
    <%= f.text_field :author, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, :abstract) do %>
    <%= f.text_area :abstract, rows: 5, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, :pages) do %>
    <%= f.text_field :pages, class: "form-control" %>
  <% end %>

  <%= bootstrap_form_field(f, :genre) do %>
    <%= f.select :genre, Book::GENRES, { prompt: "Pick one" }, { class: "form-control" } %>
  <% end %>

  <%= bootstrap_form_field(f, :published_on) do %>
    <%= f.date_select :published_on,
                      { start_year: 1800, prompt: true, order: [ :month, :day, :year ] },
                      { class: "form-control date-select" } %>
  <% end %>

  <%= bootstrap_form_field(f, :image_file_name) do %>
    <%= f.text_field :image_file_name, class: "form-control" %>
  <% end %>

  <p>
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', @book.id ? book_path(@book) : books_path, class: 'btn btn-link' %>
  </p>
<% end %>

app/views/books/_list.html.erb
<div id="books">
<% books.each do |book| %>
  <div class="row well">
    <div class="col-sm-2">
      <%= link_to(book) do %>
      <%= image_for(book) %>
      <% end %>
    </div>
    <div class="col-sm-10">
      <h3><%= link_to(book.title, book) %> <small>by <%= book.author %></small></h3>
      <p>
      <%= render partial: 'average_stars', locals: { book: book } %>
      </p>
    </div>
  </div>
<% end %>
</div>

<div>
  <div class="pull-left page-entries-info">
  <%= page_entries_info books %>
  </div>

  <div class="pull-right">
  <%= paginate books %>
  </div>
</div>

app/views/books/bargains.html.erb
<header>
  <h3>Bargain Books</h3>
</header>

<%= render partial: 'list', locals: { books: @books } %>

app/views/books/edit.html.erb
<div class="row">
  <h2>Editing <%= @book.title %></h2>

  <%= render 'form' %>
</div>

app/views/books/index.html.erb
<header>
  <h3>All Books</h3>
</header>

<%= render partial: 'list', locals: { books: @books } %>

app/views/books/new.html.erb
<div class="row">
  <h2>Create a New Book</h2>

  <%= render 'form' %>
</div>

app/views/books/show.html.erb
<article class="book">
  <header>
    <h2 class="text-primary"><%= @book.title %></h2>
    <aside class="book-cover">
      <%= image_for(@book) %>
    </aside>
  </header>
  <p><%= @book.abstract %></p>

  <section>
    <header><h4 class="text-primary">Details</h4></header>

    <p>
      <label>Author:</label>
      <%= @book.author %>
    </p>
    <p>
      <label>Genre:</label>
      <%= @book.genre %>
    </p>
    <p>
      <label>Pages:</label>
      <%= number_with_delimiter(@book.pages) %>
    </p>
    <p>
      <label>Published On:</label>
      <%= @book.published_on %>
    </p>
    <p>
      <label>Average Review:</label>
      <span id="average_review">
      <%= render partial: 'average_stars', locals: { book: @book } %>
      </span>
    </p>
  </section>

  <section>
    <header><h4 class="text-primary">Download a book</h4></header>
    <% if @book.assets.any? %>
        <% @book.assets.each do |asset| %>
        <p>Download in
            <span id="read_reviews">
              <%= link_to asset.asset_url.to_s.split('.').last, asset.asset_url %>
            </span><br/>
        </p>
        <% end %>
    <% else %>
      <p>
        There is no book formats available
      </p>
      <ol id="reviews"></ol>
    <% end %>
  </section>

  <section>
    <header><h4 class="text-primary">Recent Reviews</h4></header>
    <% if @book.recent_reviews.any? %>
      <%= render partial: 'shared/reviews', locals: { reviews: @book.recent_reviews } %>
      <p>
        Read all
        <span id="read_reviews">
          <%= link_to pluralize(@book.reviews.size, 'review'), book_reviews_path(@book) %>
        </span>
      </p>
    <% else %>
      <p>
        Be the first to write a review!
      </p>
      <ol id="reviews"></ol>
    <% end %>
  </section>

  <nav>
    <%= link_to 'Write a Review', new_book_review_path(@book),
          remote: true,
          data: { 'update-target' => 'review_form_container' },
          class: 'btn btn-primary' %>
  </nav>

  <div id="review_form_container"></div>

  <% if current_user %>
      <nav id="book-show-buttons">
        <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-default' %>

        <span class='inline-button-form'>
          <%= button_to "Delete #{@book.title}", @movie,
                       method: :delete,
                       data: { confirm: 'Are you sure?' },
                       class: 'btn btn-danger' %>
        </span>
      </nav>

      <%= render "assets/upload", :book => @book %>
  <% end %>



</article>