config/routes.rb
Books::Application.routes.draw do

  devise_for :users, path_names: { sign_in: 'admin', }
  as :user do
    get "/admin" => "devise/sessions#new"
  end

  root 'books#index'

  resources :books do
    collection do
      get 'page/:page', :action => :index
    end

    resources :reviews
    resources :assets, :only => [:index, :create, :destroy, :show] do
      get 'convert'
    end
  end

  get ':genre' => 'books#index', :as => 'genre'

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| -%>
  <div class="alert alert-dismissable <%= flash_class(key) %>">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= value -%>
  </div>
<% end -%>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to('Bizdin.kg', root_path, class: 'navbar-brand')%>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%- if current_user %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
          <%-else %>
              <li class="dropdown">
                <%= link_to "Sign in", new_user_session_path %>
              </li>
          <%- end %>
        </ul>
      </div>

    </div>
  </nav>

</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" data-spy="affix" data-offset-top="100">
  <div class="panel panel-primary">
    <div class="panel-heading">
    </div>
    <div class="panel-body">
      <p>
        <%= link_to new_book_path, class: 'btn btn-default col-md-12' do %>
            <span class="pull-left glyphicon glyphicon-plus"></span> Create Book
        <% end %>
      </p>
      <p>
        <%= link_to books_path, class: 'btn btn-default col-md-12' do %>
            <span class="pull-left glyphicon glyphicon-list"></span> All Books
        <% end %>
      </p>
      <% if @genres %>
          <% @genres.each do |genre| %>
              <p>
                <%= link_to genre_path(genre), class: 'btn btn-default col-md-12' do %>
                    <span class="pull-left glyphicon glyphicon-'<%= genre %>'"></span> <%= genre %>
                <% end %>
              </p>
          <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bizdin.kg</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/layouts/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>